#!/usr/bin/env python3
import signal
import subprocess
import sys
import os
import time


def run():
    global process
    if '.py' in sys.argv[1]:
        command = ['python3'] + sys.argv[1:]
    else:
        command = sys.argv[1:]
    process = subprocess.Popen(command)
    process.communicate()
    print(f'\n{" ".join(command)}: Done')


def handle_interrupt(sig, frame):
    global process
    if process is not None and process.returncode is None:
        process.send_signal(signal.SIGINT)
    else:
        sys.exit(130)


if __name__ == '__main__':
    home = os.environ['HOME']
    global process
    process = None
    signal.signal(signal.SIGINT, handle_interrupt)

    file_path = f'{home}/.config/nvim/dog'

    last_modified = os.path.getmtime(file_path)
    while True:
        current_modified = os.path.getmtime(file_path)
        if current_modified != last_modified:
            run()
            last_modified = current_modified
        time.sleep(0.0166)  # this is 60 hz
